# Generated by Django 5.2.5 on 2025-08-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietetics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
