# Generated by Django 5.2.5 on 2025-08-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietetics', '0002_remove_users_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
