# Generated by Django 5.2.4 on 2025-09-12 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietetics', '0003_alter_users_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DejHistories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('age', models.FloatField()),
                ('nap', models.FloatField()),
                ('title', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImcHistories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SriHistories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('previous_weight', models.FloatField()),
                ('low_ingesta_five_days', models.BooleanField(default=False)),
                ('low_ingesta_ten_days', models.BooleanField(default=False)),
                ('potassium', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('atcd', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UndernutritionAdultHistories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('previous_weight', models.FloatField()),
                ('previous_weight_date', models.CharField(max_length=24)),
                ('albuminemia', models.FloatField()),
                ('sarcopenia', models.BooleanField(default=False)),
                ('etiological_food_intakes', models.BooleanField(default=False)),
                ('etiological_absorption', models.BooleanField(default=False)),
                ('etiological_agression', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UndernutritionSeniorHistories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('previous_weight', models.FloatField()),
                ('previous_weight_date', models.CharField(max_length=24)),
                ('albuminemia', models.FloatField()),
                ('sarcopenia', models.BooleanField(default=False)),
                ('etiological_food_intakes', models.BooleanField(default=False)),
                ('etiological_absorption', models.BooleanField(default=False)),
                ('etiological_agression', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
