# Generated by Django 5.2.4 on 2025-10-05 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietetics', '0004_dejhistories_imchistories_srihistories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnaldatabases',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='personnaldatabases',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_databases', to=settings.AUTH_USER_MODEL),
        ),
    ]
