# Generated by Django 5.2.4 on 2025-10-05 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietetics', '0005_personnaldatabases_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foods',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
