# Generated by Django 5.2.4 on 2025-10-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietetics', '0006_foods_created_at_foods_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='alcohol',
            new_name='alcool',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='title',
            new_name='alim_nom_fr',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='calories_kcal',
            new_name='energie_reg_ue_kcal',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='carbohydrates',
            new_name='fer',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='fats',
            new_name='fibres',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='fibers',
            new_name='glucides',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='iron',
            new_name='lipides',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='phosphorus',
            new_name='phosphore',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='proteins',
            new_name='proteines',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='sugars',
            new_name='sucres',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='vitamin_d',
            new_name='vitamine_d',
        ),
    ]
