# Generated by Django 5.2.5 on 2025-10-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietetics', '0007_rename_alcohol_foods_alcool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='user',
        ),
        migrations.DeleteModel(
            name='FoodForMeals',
        ),
        migrations.DeleteModel(
            name='Meals',
        ),
    ]
