# Generated by Django 5.2.5 on 2025-10-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietetics', '0008_remove_meals_user_delete_foodformeals_delete_meals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dejhistories',
            old_name='title',
            new_name='gender',
        ),
    ]
