# Generated by Django 5.2.5 on 2025-10-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietetics', '0009_rename_title_dejhistories_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentaries',
            new_name='Comments',
        ),
    ]
