# Generated by Django 5.2.5 on 2025-10-26 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietetics', '0010_rename_commentaries_to_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonnalDatabases',
            new_name='Foodbases',
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
