# Generated by Django 5.2.5 on 2025-10-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietetics', '0011_rename_personnaldatabases_foodbases_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodbases',
            options={'ordering': ['-created_at'], 'verbose_name': 'Base alimentaire personnelle', 'verbose_name_plural': 'Bases alimentaires personnelles'},
        ),
        migrations.AlterModelOptions(
            name='foods',
            options={'ordering': ['-created_at'], 'verbose_name': 'Aliment', 'verbose_name_plural': 'Aliments'},
        ),
    ]
